### PR TITLE
Fix bug where iOS system status was not updating quickly enough

### LINKED ISSUE #861: HomeScreen - showing "all set" when Covid Alert is off
The HomeScreen view is showing "all set" status when Covid Alert is off (or in an unknown / undefined state).

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #861 (Part of #857)

Added logic to set systemStatus to disabled if we have an iOS error indicating the user has disabled the framework. I am just checking against a string right now but I know this is not the correct way to check the type of error. @henrytao-me do you know how to do that properly?

Screen Shot 2020-07-23 at 11 11 47 AM

### CODE REVIEW

File: src/services/ExposureNotificationService/ExposureNotificationService.ts [hunk 1]
```diff
@@ -131,6 +131,10 @@ export class ExposureNotificationService {
       await this.exposureNotification.start();
     } catch (error) {
       captureException('Cannot start EN framework', error);
+      if (error.message === 'ENErrorCodeNotAuthorized (User denied)') {
```
Comment (timarney) [inline src/services/ExposureNotificationService/ExposureNotificationService.ts:134]: I think we can use just the "ENErrorCodeNotAuthorized" part of the message or use the error code.  Preferably the error code if possible.

File: src/services/ExposureNotificationService/ExposureNotificationService.ts [hunk 2]
```diff
@@ -131,6 +131,12 @@ export class ExposureNotificationService {
       await this.exposureNotification.start();
     } catch (error) {
       captureException('Cannot start EN framework', error);
+      // 4: 'ENErrorCodeNotAuthorized (User denied)'
+      // https://developer.apple.com/documentation/exposurenotification/enerrorcode/enerrorcodenotauthorized?language=objc
+      if (error.code === '4') {
```
Comment (timarney) [inline src/services/ExposureNotificationService/ExposureNotificationService.ts:136]: @henrytao-me we've opted to handle this based on the error code - any comments?

File: src/services/ExposureNotificationService/ExposureNotificationService.ts [hunk 3]
```diff
@@ -132,10 +132,10 @@ export class ExposureNotificationService {
     } catch (error) {
       captureException('Cannot start EN framework', error);
       this.systemStatus.set(SystemStatus.Unknown);
-      return;
     }
 
     await this.updateSystemStatus();
+    console.log('this.systemStatus.get()', this.systemStatus.get());
```
Comment (henrytao-me) [inline src/services/ExposureNotificationService/ExposureNotificationService.ts:138]: Remove this.

Comment (timarney) [reply src/services/ExposureNotificationService/ExposureNotificationService.ts:138]: Please :)

Comment (smcmurtry) [reply src/services/ExposureNotificationService/ExposureNotificationService.ts]: whoops!
